### ISSUE TITLE
extra module not needed

### ISSUE THREAD

**Issue by steveklabnik** [Okasu/weather-rs#1]
Hey there! you said you wanted some feedback on reddit, and I don't have a ton of time to dig into a lot of things, but one thing did pop up.

https://github.com/Okasu/weather-rs/blob/master/src/lib.rs#L9

This is probably a bit too nested. It really depends if you're planning on adding other backends for this, and if you are, then it's sort of the reverse: too much is within the `wunderground` namespace. Does that make sense?

Like, here: https://github.com/Okasu/weather-rs/blob/master/src/main.rs#L5 you end up having to import everything through this module anyway; the top-level 'weather' module is pretty much useless.

**Comment by gsmnv** [comment]
@steveklabnik Awesome, thank you for feedback! Yeah, I really do plan to add other back-ends for this in case if Wunderground will change or remove their free API access plan or I'll find some better/more accurate alternative to Wunderground. 
Initially I haven't got that `wunderground` namespace but later on I've realized that there is not much to share between different back-ends so I've ended up with this isolated `wunderground` module. Of course if there will be something to share between different back-ends I'll put it in "top level" module.
